name: Build Django-PostgreSQL-Reconnect library

on:
  push:
    branches: '*'
    tags:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and test on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    services:
      postgres:
        image: postgres:11.5
        ports:
        - 5432:5432
        env:
          POSTGRES_PASSWORD: 1q2w3e
          POSTGRES_DB: django_postgresql_reconnect
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Linting
        run: |
          poetry run flake8
      - name: Testing
        run: |
          poetry run pytest
        env:
          POSTGRES_HOST: localhost
  sonar:
    name: Quality Analysis by sonar
    needs: [build]
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11.5
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: 1q2w3e
          POSTGRES_DB: django_postgresql_reconnect
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Testing
      run: |
        poetry run pytest
      env:
        POSTGRES_HOST: localhost
    - name: Fix coverage report for Sonar
      run: |
        sed -i 's/\/home\/runner\/work\/django-postgresql-reconnect\/django-postgresql-reconnect\//\/github\/workspace\//g' ./tests/reports/coverage.xml
    - name: SonarCloud
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Wait sonar to process report
      uses: jakejarvis/wait-action@master
      with:
        time: '15s'
    - name: SonarQube Quality Gate check
      uses: sonarsource/sonarqube-quality-gate-action@master
      timeout-minutes: 5
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
